/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *   Copyright (C) 2009 icepir8                                            *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.          *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef __DEBUG_H
#define __DEBUG_H

//#define WRITE_LOG

#define PRINT_RDP_NOT_IMPLEMENTED(x) PRINT_RDP_INFO(x)
#define PRINT_RDP_WARNING(x) PRINT_RDP_INFO(x)

extern void PRINT_RDP_MNEMONIC(char *fmt, ...);
extern void PRINT_RDP_INFO(char *text);

extern void LOG_TO_FILE(char *fmt, ...);

extern void DebugBox(char *fmt, ...);

#endif


