######################################################################
# Automatically generated by qmake (2.01a) Fri May 16 00:15:22 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
